### ISSUE TITLE
need stable CI builds on master

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/froto#110]
I was expecting `0.7.1` to be built from master after merging #108 , but https://github.com/AArnott/Nerdbank.GitVersioning/issues/375

**Comment by ctaggart** [comment]
CI builds are being published to https://www.myget.org/feed/Packages/froto
cc @jhugard @takemyoxygen

**Comment by ctaggart** [comment]
Fixed by #113

0.7.2 is now in the NuGet Gallery. 
@takemyoxygen, looks like https://www.nuget.org/packages/Froto.TypeProvider.DesignTime is new.

**Comment by takemyoxygen** [comment]
@ctaggart I don't think `Froto.TypeProvider.DesignTime` needs a separate package. `Runtime` and `DesignTime` assemblies together (and all its dependencies) are published as single https://www.nuget.org/packages/Froto.TypeProvider/ package

**Comment by ctaggart** [comment]
Okay, I’ll unlist it.

**Comment by ctaggart** [comment]
I helped add support for GitHub Actions to GitVersioning and this is working now. Fixed in #113
