### ISSUE TITLE
froto.exe support for protobuf-net proto2 code generation 

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/froto#17]
Now that `froto.exe` has been created #11. We need to get the existing protobuf-net proto2 code generation working.

**Comment by ctaggart** [comment]
@jhugard Would you like this issue?

**Comment by jhugard** [comment]
I can take it eventually, but IMHO the C# object model should be fleshed-out and finished first, as well as getting the Roslyn code generation fully unit tested.  I'm not certain, but I think datatypes, such as sint32 and binary, are not properly handled.

Plus, my current need is to have .NET code which can deserailize binary proto2 FileDescriptorProto and FileDescriptorSet into objects to read off custom options, etc. for a prototype I'm building.

So, I'd prefer to put this off for a while...

**Comment by ctaggart** [comment]
This is very low priority and may even be dropped now that you've done so much work on `Froto.Core`.

**Comment by ctaggart** [comment]
For now, closing this in favor of #15 which will use Froto.Core and #3 which will use Froto.Core.
