### ISSUE TITLE
Linux / mono build not working

### ISSUE THREAD

**Issue by jhugard** [ctaggart/froto#18]
The Roslyn bits (and hence Exe) have a dependency on `Microsoft.CodeAnalysis.CSharp.Workspaces`, which in turn were built to target .NET 4.5.2.  However, mono / monodevelop don't (yet) appear to support that version so the build fails, even if those projects are set to target 4.5(.0).

Tried several ways to fix this up, but hit the limits of my Linux knowledge.

**Comment by ctaggart** [comment]
I'll have a look. Thank for reporting.
