### ISSUE TITLE
publish Froto.Core NuGet package

### ISSUE THREAD

**Issue by takemyoxygen** [ctaggart/froto#29]
In the [Readme](https://github.com/ctaggart/froto/blob/master/readme.md) it's mentioned that Froto.Core package already exists, but I can't find it on NuGet. Am I missing something or it has been removed?

I'm interested in using this package since I've started working on a [type provider for Protocol Buffers](https://github.com/takemyoxygen/ProtoTypes). I use Froto.Parser already, but it would be nice to be able to reuse serialization code as well.

Let me know if I can help somehow.

**Comment by ctaggart** [comment]
Awesome! Feel free to contribute that here. I haven't published it yet the the NuGet Gallery. I will now (cc @jhugard). The prerelease builds are available from the AppVeyor feed. I should put that in the readme.

list of builds: https://ci.appveyor.com/project/ctaggart/froto/history
feed url: https://ci.appveyor.com/nuget/ctaggart-froto

**Comment by ctaggart** [comment]
published
https://www.nuget.org/packages/Froto.Core/0.2.1
https://www.nuget.org/packages/Froto.Parser/0.2.1

fyi, this was the build log
https://ci.appveyor.com/project/ctaggart/froto/build/0.2.1

**Comment by takemyoxygen** [comment]
Fantastic! Thanks a lot!
