### ISSUE TITLE
F# type provider for .proto files

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/froto#3]
I'm going to remove my first attempt at building the type provider prototype. It was a wrapper around Froto.Roslyn that I called Froto.Gen. Removing it for now.

**Comment by ctaggart** [comment]
For now, this is out of scope. I'm going to generate code for v3 of Protocol Buffersvia F# AST code generation. See https://github.com/ctaggart/FsAst
#6

**Comment by ctaggart** [comment]
@takemyoxygen mentioned in #29 that he has started working on a Type Provider. I would love to see it incorporated as part of froto. I'm happy to give commit access after a couple of pull requests.

https://github.com/takemyoxygen/ProtoTypes

We can discuss NuGet package names, but something like `Froto.TypeProvider` would be great.

**Comment by takemyoxygen** [comment]
I'd be happy to merge my repo into Froto. But first, I guess, I'll try to implement some very basic type provider based on Froto.Parser and Froto.Core, and then I'll create a PR to merge that.

**Comment by ctaggart** [comment]
With Don tweeting about this, I see it got a whole bunch of attention.
https://twitter.com/dsyme/status/735247215086739457

@takemyoxygen Anything that you need from Froto.Core or Froto.Parser? I really like that @jhugard is looking at F# Record Serialization.

**Comment by takemyoxygen** [comment]
@ctaggart I think I don't need anything for now. 
Btw, I guess on the next week I'll start integrating it to Froto.

**Comment by takemyoxygen** [comment]
@ctaggart, I'd like to import initial version of the type provider into froto. I think it would make sense to merge it into a separate branch first, as there are still a lot of things to do there, and I'd prefer to do smaller PRs and more often. Could you create a separate branch for the type provider in this repository?

**Comment by ctaggart** [comment]
@takemyoxygen You've been invited to collaborate. Creating a separate branch sounds good. Go for it!
https://github.com/ctaggart/froto/invitations

**Comment by jhugard** [comment]
Closing this issue in favor of starting fresh with #49.
