### ISSUE TITLE
Dehydrating functions  for unsigned arithmetic types

### ISSUE THREAD

**Issue by tathanhdinh** [ctaggart/froto#33]
Hello everyone,
Many thanks for this library, I just start trying to use it for my personal project. In the `Serializer` module, I observe that there are [`dehydrating functions`](https://github.com/ctaggart/froto/blob/master/Core/Serializer.fs#L203-L232) for only signed arithmetic types. So how can I encode unsigned types?

**Comment by jhugard** [comment]
Can you please post a failing example, along with the compiler error (and reopen this issue)?  All the numeric dehydrate functions should work on any value that implements op_Explicit, which includes all unsigned numeric types (they get converted to uint64 before serialization).

```
    /// Generic Dehydrate for all varint types, excepted for signed & bool:
    ///   int32, int64, uint32, uint64, enum
    let inline dehydrateDefaultedVarint d fldNum v = elided d v <| WireFormat.encodeFieldVarint fldNum (uint64 v)

```

**Comment by tathanhdinh** [comment]
Many thanks @jhugard. I am very sorry, I have misunderstood the meaning of these functions (I thought that, e.g. `dehydrateDefaultedSInt32` is for encoding `int32`). But what is the difference between `int32` and a "signed" type `sint32`?

**Comment by jhugard** [comment]
Signed Integer protobuf types encode small negative values in as little as one (1) byte, whereas regular integers always encode negative values in ten (10) bytes, regardless of value.  See the Google Protobuf encoding specification: https://developers.google.com/protocol-buffers/docs/encoding#signed-integers for more detail.
