### ISSUE TITLE
Feasible to port it to other languages 

### ISSUE THREAD

**Issue by kanekotic** [ctaggart/froto#4]
Hi I saw your package the other day going around nuget. First of all I think is a Great Idea.

Maybe I am a bit confused on what you are trying to achive, let me know if I am far away from your concept. Are you trying to do the compilation or add support to F# of protocol buffers?.

I am interested in adding support for compilation for C# projects. On Proto files compilation I have done this work using [node.js+protoc scripts](https://github.com/Hatisoft/ProtoToCs) but on my project I still have to add the things manually to the project. I think going through roslyn sounds great idea.

I have just started doing also some extensions for roslyn so I would be interested on helping you on this specially for C# projects. If you want a hand lets think how can I help, hopefully we can find a way to make it work for CLI bassed languages (F# and C#).

**Comment by ctaggart** [comment]
The original idea over 3 years ago was to create a parser for .proto files that could be used to generate code. After that, I generated the C# code for protobuf-net from a .proto file using early versions of Roslyn. I then tried to wrap some of that into a F# TypeProvider. I posted some blogs about it: http://blog.ctaggart.com/2012/11/parsing-protocol-buffers-proto-file-in-f.html?q=protobuf

Update to today, and I may have a need for it. Google is working on v3 of Protocol Buffers, see #6. They will actually support C# out of the box.

https://developers.google.com/protocol-buffers/docs/csharptutorial
https://developers.google.com/protocol-buffers/docs/reference/csharp/

I may attempt soon to support generating F# code soon that uses `nuget Google.Protobuf -prerelease` for v3. Other language support may be possible.
