### ISSUE TITLE
Encoding of fixed and sfixed types

### ISSUE THREAD

**Issue by takemyoxygen** [ctaggart/froto#45]
It looks to me that there's some inconsistency in `Encode` module:
1. `Encode.fromFixed32` should take `uint32` value as a parameter rather than `int`, then it would match `Decode.toFixed32` which returns `uint32` already
2. `Encode.fromFixed64` should take `uint64` value as a parameter rather than `int`, then it would match `Decode.toFixed64` which returns `uint64` already
3. There's no function `Encode.toSFixed32` taking `int32`, but dual function `Decode.toSFixed32` already exists
4. There's no function `Encode.toSFixed64` taking `int64`, but dual function `Decode.toSFixed64` already exists

I consider [this page](https://developers.google.com/protocol-buffers/docs/proto3#scalar) as the source of mappings from protobuf scalar types to .NET ones.

If that's indeed something that needs to be fixed, let me know and I'll have a look.

**Comment by jhugard** [comment]
I'll take a look this weekend.  I may have wanted some of those functions to be polymorphic across anything with member `op_Explicit`, but more likely you are right and that was inadvertently inherited from the underlying cast to `uint32` in `fromDefaultedFixedXX`.

**Comment by jhugard** [comment]
@takemyoxygen - Yup, good find!
In addition, Encode.fromPackedFixed32/64 had the wrong type(s) and Encode.fromPackedSFixed32/64 were missing.  Adding these + fixing/extending/adding unit tests.

**Comment by takemyoxygen** [comment]
@jhugard great, thanks!
