### ISSUE TITLE
F# Type Provider for .proto Files

### ISSUE THREAD

**Issue by jhugard** [ctaggart/froto#49]
Create an F# Type Provider which reads .proto Files and produces classes for serializing and deserializing to protobuf wireformat.

This is being iterated on in branch [type-provider](https://github.com/ctaggart/froto/tree/type-provider).

**Non-goals**

 - Generation of `service` wrapper classes.
 - Importing from binary (compiled .proto) `FileDescriptorSet`.

**Comment by ctaggart** [comment]
@jhugard Feel free to tag a 0.4.0 if @takemyoxygen is ready to release the type provider. I'm on vacation for a week, but there is strong interest from my employer in looking at grpc and it could get me back more involved in this.

**Comment by takemyoxygen** [comment]
@jhugard @ctaggart I think it's ready for the initial release. I'll also have a closer look at grpc to see if type provider can be of any help there.

**Comment by ctaggart** [comment]
Publishing 0.4.0 today. Working on it right now.
