### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by xenocons** [ctaggart/froto#56]
Both FAKE and msbuild directly fail to build the froto project from a fresh git clone due to a missing library. 

### Resolution:
Add `nuget System.Collections.Immutable` to paket.dependencies.
Add `System.Collection.Immutable` to project Froto.Roslyn and Froto.Roslyn.Test.

**Comment by takemyoxygen** [comment]
As far as I see, `System.Collections.Immutable` is both in `paket.lock` (so the package should be restored) and in both `Froto.Roslyn.fsproj` and `Froto.Roslyn.Tests.fsproj`, so there should be no need to reference this package explicitly in `paket.dependencies`.

Are you building on Windows or on Linux/OS X (which version of mono)?

**Comment by xenocons** [comment]
Ok, this is PEBKAC, the reason this error occurred (and https://github.com/ctaggart/froto/issues/57) was due to me having an incorrect order of running things (I was initialising packet with `paket.bootstrapper.exe && paket.exe update` as opposed to `paket.bootstrapper.exe && paket.exe restore`

This may seem obvious, but to me it was because I was looking at the directory, and not seeing the regular `build.cmd` that exists in scaffold projects, I mistakenly thought `build.ps1` was the update of that, however upon looking at `build.ps1` it is very different from `build.sh` (infact `build.sh` does the paket restore properly).

I suggest to prevent confusion, adding back the `build.cmd` into the repo (https://github.com/fsprojects/ProjectScaffold/blob/master/build.cmd)
