### ISSUE TITLE
Froto.Compiler Dependency

### ISSUE THREAD

**Issue by xenocons** [ctaggart/froto#57]
It appears System.Reflection.Metadata is missing from the project references for Froto.Compiler, this package is available in nuget.

### Resolution
Update paket.dependencies to include `nuget System.Reflection.Metadata`
Update paket.references in Froto.Compiler to include `System.Reflection.Metadata`

**Comment by takemyoxygen** [comment]
this package is referenced already in `Froto.Compiler.fsproj`

**Comment by xenocons** [comment]
As per above issue, this was due to missing the paket restore step in the initial build process (user error!), see #57 for more info.
