### ISSUE TITLE
Example Autogen

### ISSUE THREAD

**Issue by xenocons** [ctaggart/froto#59]
Hi,

Not really an issue... but I was wondering what library call was used to autogenerate https://github.com/ctaggart/froto/blob/master/Serialization.Test/ExampleProtoRecord.fs ?

**Comment by jhugard** [comment]
Sorry if this was/is misleading: code generation is not yet implemented.  This definition, and similar ones, were hand crafted to help refine what generated code should look like and to allow development of support code for eventual code generation.

**Comment by xenocons** [comment]
no worries! understand its a in progress thing!
