### ISSUE TITLE
Feature: Add support for Proto3 language

### ISSUE THREAD

**Issue by jhugard** [ctaggart/froto#6]
Requesting simultaneous support for both proto2 and proto3 language syntax, selected via the new `syntax = "[proto2|proto3]";` statement.

https://developers.google.com/protocol-buffers/docs/reference/proto3-spec

As possible incentive, [the official C# generator for Proto3](https://developers.google.com/protocol-buffers/docs/reference/csharp-generated) does not ([and will not](https://groups.google.com/d/msg/protobuf/9QfbvKh4I2I/i9MGMztaCAAJ)) support generating code for the proto2 language, and thus it is not (and will-not-be) possible to write protobuf tooling and self-describing services in .NET.

Perhaps Froto can be used to fill that need.

**Comment by ctaggart** [comment]
Why is it not possible to write self-describing services in .NET for Protocol Buffers v3? What do you mean by self-describing services? Do you mean code-first with attributes like:
https://github.com/mgravell/protobuf-net#1-first-decorate-your-classes

**Comment by jhugard** [comment]
Have in mind to create a service registration protocol which allows a generic service to register it's FileDescriptorProto (or Set) at run-time, so that the service's metadata can be inspected as well as to provide transcoding from/to JSON, without recompiling the server being registered with.  That's what I meant by "self-describing services".

The official C# generator from Google will not generate code for proto2, but proto2 is required if one wants to define _and process_ custom options in .NET.  So... I am hunting for an alternative.

**Comment by ctaggart** [comment]
I had to read up more about `custom options`. I have't used them, but they could be useful for altering the code generation. It looks to me like you can put custom options in a proto3 descriptor. Did I miss something?

https://developers.google.com/protocol-buffers/docs/proto#options
https://developers.google.com/protocol-buffers/docs/proto3#options
https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L35-L37

**Comment by jhugard** [comment]
Hah.  What you missed is that while custom options can be _used_ in proto3, they require proto2 syntax to _define_ (custom options use the ```extend``` keyword, which is proto2 only).  Further, the Google C# code generator only supports generating proto3 constructs, so while it will recognize custom options, it will not generate code to access them. :P
