### ISSUE TITLE
Produce Portable Class Library (PCL)

### ISSUE THREAD

**Issue by jhugard** [ctaggart/froto#67]
None of the Froto libraries are Portable Class Libraries, so they cannot be included in other PCL projects.

It would be useful to, at minimum, produce Froto.Serialization as a PCL.

**Comment by takemyoxygen** [comment]
Any particular platform you have in mind? Maybe switch to .NET Core?

**Comment by ctaggart** [comment]
I plan to see about switching to .NET Core with the next release candidate of Visual Studio & .NET Core. The msbuild support was just too unstable last time I tried it out in late November.

**Comment by jhugard** [comment]
@ctaggart Sounds great!  The lower the .NET Core version, the better, as the lower versions provide broader mapping to the various mobile-compatible profiles.

**Comment by ctaggart** [comment]
FYI, I tried out Visual Studio 2017 RC3 last week to see if it is ready. It is not. Need to wait for the next RC or RTM.

**Comment by takemyoxygen** [comment]
@ctaggart, do you mean the IDE itself or .NET Core tooling? I use VS 2017 almost every day for C# development. Works more or less ok for me.

**Comment by ctaggart** [comment]
@takemyoxygen My comments are regarding the F# tooling in VS 2017 RC3. Yes, C# is working well.

**Comment by ctaggart** [comment]
I'm going to make migrate to the .NET Core project tooling #73. We can then decide what we wish to target for .NET Standard in a separate issue.
