### ISSUE TITLE
TypeProvider fails with "Specified method is not supported"

### ISSUE THREAD

**Issue by EHotwagner** [ctaggart/froto#71]
I am trying to use blizzards sc2 proto files provided here: https://github.com/Blizzard/s2client-proto
The first problem is the use of the not supported "import" statement. I concatenated the content of the files to fix this.

Then i got the following error in debug.proto:  "Specified method is not supported"
in this section:
```protobuf
// Issue various useful commands to the game engine.
message DebugCommand {
  oneof command {
    DebugDraw draw = 1;
    //gamestatemessage is broken with the Froto Typeprovider
    //DebugGameState game_state = 2; 
    DebugCreateUnit create_unit = 3;
    DebugKillUnit kill_unit = 4;
    DebugTestProcess test_process = 5;
    DebugSetScore score = 6;                // Useful only for single-player "curriculum" maps.
    DebugEndGame end_game = 7;
    DebugSetUnitValue unit_value = 8;
    DebugChat chat = 9;                     // TODO.
  }
}

enum DebugGameState {
  show_map = 1;
  control_enemy = 2;
  food = 3;
  free = 4;
  all_resources = 5;
  god = 6;
  minerals = 7;
  gas = 8;
  cooldown = 9;
  tech_tree = 10;
  upgrade = 11;
  fast_build = 12;
}
```
Any ideas why and how to fix this?

**Comment by jhugard** [comment]
I worked on the parser but never really looked at the TypeProvider.  `DebugGameState` is the only `enum` in that list so that may be a clue.  However, I'm not sure what's wrong because the generator does appear to support enum values in a oneof (see [here](https://github.com/ctaggart/froto/blob/master/TypeProvider/Generation/OneOf.fs#L18)).

Could you try adding an `unknown=0;` as the first member of `DebugGameState`?

Are there any additional error details?  Stack trace, line numbers, etc.?

**Comment by jhugard** [comment]
@takemyoxygen could you add an `enum` to the oneof in `type_provider_test.proto ` and write a unit test?  Also might be useful to include the TypeProvider tests in the main Froto.sln.

**Comment by takemyoxygen** [comment]
@jhugard, I'll try to have a look on the weekend

**Comment by EHotwagner** [comment]
I will investigate further after the weekend. Thanks for taking a look.

**Comment by jhugard** [comment]
@EHotwagner PR #65 could probably be merged as-is to provide `import` support to the parser, but it's not hooked into the TypeProvider yet.  I'd intended to do all of Issue #48 with that PR, but might be worth merging just for what it currently does.

**Comment by ctaggart** [comment]
Sounds good @jhugard.

**Comment by EHotwagner** [comment]
I did add `unknown=0;` with no effect. A basic proto file with only DebugCommand as a message and only DebugGameState in the oneof does work tough.

The error mesage i get is: "The type provider 'Froto.TypeProvider.ProtocolBuffersTypeProviderCreator' reported an error: Specified method is not supported."

Parse.fromFile genereates a nice Ast List tough. Is the roslyn example [example](https://github.com/ctaggart/froto/blob/ba4d5e506e1be6105dc6746a08a1d6714793e8fe/Roslyn.Test/RoslynTests.fs) the current way of working without the TypeProvider?

**Comment by jhugard** [comment]
I would truly love to see you successful with F# and SC2: both are close to my heart.  However, to be honest, while Froto may be useful for some base cases it still needs some attention to get it finished it up.

Froto has three approaches from three different authors: the TypeProvider, Roslyn code gen, and a model for source gen of either [records](https://github.com/ctaggart/froto/blob/master/Serialization.Test/ExampleProtoRecord.fs) or [classes](https://github.com/ctaggart/froto/blob/master/Serialization.Test/ExampleProtoClass.fs).  The first two have some rough edges, and there isn't a released generator for the third.

If the TypeProvider isn't working for you, the Roslyn approach might be worth a try, but then again it might not support `oneof`.

As a last-ditch effort, the serializer [record model](https://github.com/ctaggart/froto/blob/master/Serialization.Test/ExampleProtoRecord.fs) is pretty simple to generate, so you could probably hand-write everything in the SC2 API in a few hours, but that kinda defeats the purpose of having an IDL.  If you do go this route, let me know and I'll try to remember how `oneof` support works.

Some time back, as an experiment I wrote a plug-in for `protoc.exe` in golang which generated code using the record model.  The result still needed hand editing to get it to compile, so was never released.  It was a bit discouraging that the resulting DLL was not significantly smaller (in bytes) than generated C++ code, which was one of my main goals.  On top of that, politically there was no way I'd be able to move the prototype into production, so never finished any of this up.

**Comment by EHotwagner** [comment]
Thanks a lot. This gives me enough points to start from.

**Comment by takemyoxygen** [comment]
@EHotwagner, @jhugard, I hope #72 should fix the `NotSupported` error. I tried to use the type provider with the proto from https://github.com/Blizzard/s2client-proto (compiled in one file, with `syntax`, `package` and `import` directives removed) and it worked fine. It still requires some work to implement `import` in the type provider.

**Comment by EHotwagner** [comment]
Great. Thx a lot.
