### ISSUE TITLE
TypeProvider.Tests failing to build on travis-ci

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/froto#75]
travis ci failing to build TypeProvider.Tests

https://github.com/ctaggart/froto/pull/74

**Comment by takemyoxygen** [comment]
@ctaggart I hope I will have some time in the coming week to have a look at the failed build.

**Comment by ctaggart** [comment]
I woke up this morning thinking we may be able to use dotnet on Travis if that helps instead of Mono, unless we want to test for Mono compatibility of course.

**Comment by ctaggart** [comment]
As of #76, I've replaced mono with dotnet. In #74, Travis is not building the TypeProvider or its tests.  In #74, I recommended that we wait for TypeProviders to support .NETStandard.
