### ISSUE TITLE
Would it be possible to get a 0.51 nuget release of the parser and serializer?

### ISSUE THREAD

**Issue by 7sharp9** [ctaggart/froto#87]

**Comment by jhugard** [comment]
@7sharp9 Releases are usually published by @ctaggart, but if it's as simple as creating a release tag on GitHub, I'll try to get to it shortly...

**Comment by ctaggart** [comment]
I can publish it today and write down instructions

**Comment by 7sharp9** [comment]
That would be great! 

Thanks!

**Comment by ctaggart** [comment]
Okay, doing this now

**Comment by ctaggart** [comment]
It looks like #85 is new work, so I'm going to tag a `0.6.0`

**Comment by ctaggart** [comment]
The process is really simple. I just created a `0.6.0` release on GitHub. I then close the related milestone milestone. The new tag triggers a new version. I log in to AppVeyor and click the `deploy` link and select `NuGet Gallery`

![image](https://user-images.githubusercontent.com/80104/39825326-205e791c-5377-11e8-9ee4-cca73417b963.png)

**Comment by jhugard** [comment]
Looks like I don't have deploy (or build) rights on AppVeyor for this.  Would you mind also deploying the 0.6.1 release?

**Comment by ctaggart** [comment]
@7sharp9 Do you have a AppVeyor account with that email address? I think that is what this error means:

![image](https://user-images.githubusercontent.com/80104/40372947-cae5f982-5db3-11e8-8e7b-0b7f692ff6b9.png)

**Comment by jhugard** [comment]
Mine should be jayhugard@hotmail.com (just checked).

**Comment by 7sharp9** [comment]
@ctaggart I thought thats what I created it with, let me check ...

**Comment by 7sharp9** [comment]
I think my GitHub auth had been revoked for some reason, it looks  to be set up now.

**Comment by ctaggart** [comment]
@7sharp9 I'm still getting the same error when I try to add `kukulcanenator@gmail.com` as a collaborator.

**Comment by 7sharp9** [comment]
Hmm I dunno, maybe googlemail vs gmail?

**Comment by ctaggart** [comment]
What does it say at https://ci.appveyor.com/profile ?

![image](https://user-images.githubusercontent.com/80104/40614932-5dec7ab8-624a-11e8-8df0-9362c8eb067c.png)

**Comment by 7sharp9** [comment]
![screen shot 2018-05-29 at 11 42 52](https://user-images.githubusercontent.com/588746/40654186-75a19648-6335-11e8-8816-90ed69476f66.png)

**Comment by ctaggart** [comment]
@7sharp9 adding `kukulcanenator@googlemail.com` worked
