### ISSUE TITLE
Enum in message body error

### ISSUE THREAD

**Issue by kevmal** [ctaggart/froto#93]
This sample from the proto3 user guide,

```
syntax = "proto3";

message SearchRequest {
  string query = 1;
  int32 page_number = 2;
  int32 result_per_page = 3;
  enum Corpus {
    UNIVERSAL = 0;
    WEB = 1;
    IMAGES = 2;
    LOCAL = 3;
    NEWS = 4;
    PRODUCTS = 5;
    VIDEO = 6;
  }
  Corpus corpus = 4;
}
```

Fails with error

```
System.FormatException: Error in Ln: 7 Col: 15
  enum Corpus {
              ^
Expecting: newline, tab, ' ', '/*', '//' or '='

   at Froto.Parser.Parse.resultOrFail[a,b](ParserResult`2 parserResult)
   at Froto.Parser.Parse.fromFileWithParser[a](FSharpFunc`2 parser, String fileName)
   at Froto.Parser.Parse.fromFile(String fileName)
   at <StartupCode$FSI_0006>.$FSI_0006.main@()
Stopped due to error```

**Comment by 7sharp9** [comment]
I should be able to look into this.

**Comment by jhugard** [comment]
Take a look at Parser.fs:485… probably just need to move the pField parser in to the end of the list.  I’ll also try to look into this shortly…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jhugard** [comment]
The previous fix was a band-aid that would break in other ways.  @kevmal, can you please try PR #107?

**Comment by ctaggart** [comment]
I'll be pushing 0.7.x to NuGet soon. Please reopen if this is still an issue.
