### ISSUE TITLE
Allow identifiers to start with underscore

### ISSUE THREAD

**Issue by kevmal** [ctaggart/froto#94]
As titled. This 
```
syntax = "proto3";

message SearchRequest {
  string _query = 1;
}
```
Should be valid.

**Comment by jhugard** [comment]
According to the [proto2](https://developers.google.com/protocol-buffers/docs/reference/proto2-spec) and [proto3 language specifications](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec), identifiers (`ident`) must start with a letter, optionally followed by one or more letters, digits, or underscores.  A leading underscore is not a valid identifier.
