### ISSUE TITLE
Make TP work with .NET Core tooling

### ISSUE THREAD

**Issue by dsyme** [ctaggart/froto#99]
Just recording an issue that the type provider can now be updated to work with .NET Core tooling

The template for type providers is the best guide for the structure to use, for both project and package layout, https://github.com/fsprojects/FSharp.TypeProviders.SDK#the-f-type-provider-sdk

    dotnet new -i FSharp.TypeProviders.Templates
    dotnet new typeprovider -n LemonadeProvider -lang F#

**Comment by ctaggart** [comment]
Thanks @dsyme. So [jet/falanx](https://github.com/jet/falanx) is a code generator that uses Froto.Parser to generate code that uses Froto.Serialization. I had the chance to look through the code earlier this week and it is my understanding that a type provider is being [used internally](https://github.com/jet/falanx/blob/master/Falanx.Proto.Generator/CreateProto.fs#L19) internally. Some questions for @7sharp9:

- Could that type provider be make public?
- Can I take another type provider such as OpenAPITypeProvider and use some of Falanx.Machinery code to generate F# code?

It would be amazing if you could generate F# code from any type provider. I need to generate code for use with Swagger v2 or OpenAPI v3 specs. I want the generated code to build HttpClient [typed clients] (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1#typed-clients). It would be great I could use the same code to support a type provider or generated F# code.

**Comment by ctaggart** [comment]
Fixed by @takemyoxygen in #102 and is on `master`.
